import fs from 'node:fs';
import path from 'node:path';
import {marked} from 'marked';
const read = p => JSON.parse(fs.readFileSync(p,'utf8'));
const esc = s => String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const all = fs.readdirSync('content/insights').filter(f=>f.endsWith('.json')).map(f=>read('content/insights/'+f));
const entries = all.filter(p=>p.published).sort((a,b)=>b.date.localeCompare(a.date));
const tracks = read('content/tracks.json');
const projects = read('content/projects.json');
const slugs = new Set();
for (const p of entries) {
 if (!/^[a-z0-9-]+$/.test(p.slug) || slugs.has(p.slug)) throw new Error('Invalid or duplicate slug: '+p.slug);
 slugs.add(p.slug);
 for (const key of ['title','date','summary','topic','type']) if (!p[key]) throw new Error(`Missing ${key}: ${p.slug}`);
 if (!/^\d{4}(-\d{2}(-\d{2})?)?$/.test(p.date)) throw new Error('Invalid date: '+p.slug);
 for (const key of ['cover','attachment']) if (p[key] && (!p[key].startsWith('/') || p[key].includes('..') || !fs.existsSync('.'+p[key]))) throw new Error('Missing/invalid asset: '+p[key]);
}
// Render only published content to an isolated public directory.
fs.rmSync('dist',{recursive:true,force:true});
fs.mkdirSync('dist/posts/pdfs',{recursive:true});
if(fs.existsSync('assets')) fs.cpSync('assets','dist/assets',{recursive:true});
for(const entry of entries) for(const key of ['cover','attachment']) if(entry[key]) {
 const target='dist'+entry[key];fs.mkdirSync(path.dirname(target),{recursive:true});fs.copyFileSync('.'+entry[key],target);
}
for (const file of ['site.css','site.js']) fs.copyFileSync(file,'dist/'+file);
const nav = [['Home','index.html'],['Insights','insights.html'],['Future Map','future.html'],['Projects','projects.html'],['About','about.html']];
function page(file,title,body,active='Home',description='Research by Donald Lai on AI systems, emerging technology and long-term industry change.') {
 const prefix=file.includes('/')?'../':'';
 const canonical='https://lll1111111.github.io/'+(file==='index.html'?'':file);
 const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | Donald Lai</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${canonical}"><meta property="og:title" content="${esc(title)} | Donald Lai"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:url" content="${canonical}"><meta property="og:image" content="https://lll1111111.github.io/assets/context-preview.jpg"><link rel="alternate" type="application/rss+xml" title="Donald Lai Insights" href="${prefix}feed.xml"><link rel="stylesheet" href="${prefix}site.css"><script src="${prefix}site.js" defer></script></head><body><a class="skip" href="#main">Skip to content</a><header class="header"><a class="brand" href="${prefix}index.html">DL<span class="brand-dot">.</span><span class="brand-name">Donald Lai<small>Independent perspectives</small></span></a><nav aria-label="Main navigation">${nav.map(([n,u])=>`<a ${n===active?'aria-current="page"':''} href="${prefix+u}">${n}</a>`).join('')}</nav><a class="social" href="https://x.com/donaldlai3000" aria-label="Donald Lai on X">X ↗</a></header><main id="main">${body}</main><footer><div><a class="footer-name" href="${prefix}about.html">Donald Lai<span>.</span></a><p>Technology. Systems. Long-term thinking.</p></div><div><a href="https://x.com/donaldlai3000">X ↗</a><a href="https://github.com/LLL1111111">GitHub ↗</a><a href="${prefix}feed.xml">RSS ↗</a><small>© ${new Date().getFullYear()} Donald Lai · Personal research, not investment advice.</small></div></footer></body></html>`;
 fs.mkdirSync(path.dirname('dist/'+file),{recursive:true});fs.writeFileSync('dist/'+file,html);
}
const intro=(tag,title,desc)=>`<section class="page-intro wrap"><p class="eyebrow">${tag}</p><h1>${title}</h1><p class="lead">${desc}</p></section>`;
const heading=(tag,title,link='')=>`<div class="section-heading"><div><p class="eyebrow">${tag}</p><h2>${title}</h2></div>${link}</div>`;
const row = p=>`<article class="entry" data-year="${esc(p.date.slice(0,4))}" data-topic="${esc(p.topic)}" data-type="${esc(p.type)}" data-featured="${!!p.featured}"><time>${esc(p.date)}</time><div><p class="eyebrow">${esc(p.type)} · ${esc(p.topic)}</p><h3><a href="posts/${p.slug}.html">${esc(p.title)}</a></h3><p>${esc(p.summary)}</p></div><a class="entry-arrow" href="posts/${p.slug}.html" aria-label="Read ${esc(p.title)}">↗</a></article>`;
const featured = entries.find(p=>p.featured && p.cover) || entries.find(p=>p.cover);
page('index.html','Home',`<section class="home-intro wrap"><p class="eyebrow"><span class="status-dot"></span> CONTRARIAN PERSPECTIVE IN AI</p><h1>Donald Lai<span>.</span></h1><div class="intro-bottom"><p class="manifesto">Connecting AI systems<br>to what comes next.</p><div><p>I explore how technical constraints shape products, industries and long-term investment opportunities.</p><a class="primary-link" href="insights.html">Explore my research <span>↗</span></a><a class="text-link" href="about.html">About me ↗</a></div></div></section><section class="wrap questions">${heading('THE QUESTIONS BEHIND THE RESEARCH','Follow the changing constraints.')}<div class="question-grid">${tracks.filter((_,i)=>i!==2).map((t,i)=>`<a href="future.html#${t.id}"><span class="number">0${i+1}</span><h3>${esc(t.question)}</h3><p>${esc(t.position)}</p><span class="eyebrow">${esc(t.title)} ↗</span></a>`).join('')}</div></section>${featured?`<section class="feature-band"><div class="wrap">${heading('SELECTED RESEARCH','A closer look.', '<a href="insights.html">All insights ↗</a>')}<article class="feature"><a class="cover" href="posts/${featured.slug}.html"><img src="${featured.cover}" alt="First page of the original context engineering research deck" width="1200" height="675"></a><div><p class="eyebrow">${esc(featured.type)} / ${esc(featured.date)}</p><h2><a href="posts/${featured.slug}.html">${esc(featured.title)}</a></h2><p>${esc(featured.summary)}</p><a class="primary-link" href="posts/${featured.slug}.html">Read the research ↗</a></div></article></div></section>`:''}<section class="wrap section">${heading('FUTURE MAP','Four threads. One evolving perspective.','<a href="future.html">Open the map ↗</a>')}<div class="map-strip">${tracks.map((t,i)=>`<a href="future.html#${t.id}"><span class="number">0${i+1}</span><h3>${t.title}</h3><p>${t.question}</p><span>Explore direction ↗</span></a>`).join('')}</div></section><section class="wrap section">${heading('THE NOTEBOOK','Latest research','<a href="insights.html">Browse archive ↗</a>')}${entries.slice(0,3).map(row).join('')}</section><section class="about-band"><div class="wrap"><p class="eyebrow">RESEARCH INTO PRACTICE</p><h2>Ideas deserve to be tested.</h2><p>Workload analysis, research frameworks and structured investigations connect the writing to practical questions.</p><a href="projects.html" class="primary-link">Explore projects ↗</a></div></section>`);
const topics=[...new Set(entries.map(p=>p.topic))],years=[...new Set(entries.map(p=>p.date.slice(0,4)))],types=[...new Set(entries.map(p=>p.type))];
page('insights.html','Insights',intro('THE RESEARCH LIBRARY','Insights<span>.</span>','Essays, research decks and field notes on the systems shaping what comes next.')+`<section class="wrap library"><form class="filters" role="search"><label class="search-label">Search<input id="search" type="search" placeholder="Search ideas, titles, topics…"></label><label>Year<select id="year"><option value="">All years</option>${years.map(x=>`<option>${x}</option>`).join('')}</select></label><label>Topic<select id="topic"><option value="">All topics</option>${topics.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><label>Format<select id="type"><option value="">All formats</option>${types.map(x=>`<option>${x}</option>`).join('')}</select></label><button type="reset">Reset</button></form><div class="library-bar"><div class="view-toggle" aria-label="Library view"><button data-view="all" aria-pressed="true">All research</button><button data-view="featured" aria-pressed="false">Selected</button></div><p id="result-count" aria-live="polite">${entries.length} publication${entries.length===1?'':'s'}</p><a href="notes.html">Notes on X ↗</a></div><div class="timeline" tabindex="0" aria-label="Publication years"><button data-year="">All years</button>${years.map(y=>`<button data-year="${y}">${y}<span>${entries.filter(p=>p.date.startsWith(y)).length} published</span></button>`).join('')}</div><div id="entries">${entries.map(row).join('')}</div><p id="empty" hidden>No matching research. Try another topic or reset the filters.</p></section>`,'Insights');
page('future.html','Future Map',intro('A LIVING RESEARCH AGENDA','Future Map<span>.</span>','Follow the questions, the evidence and the evolution of my research across technology and industry.')+`<section class="wrap"><nav class="track-nav" aria-label="Research directions">${tracks.map((t,i)=>`<a href="#${t.id}">0${i+1} ${esc(t.title)} ↘</a>`).join('')}</nav><p class="map-caption">Research directions synthesised from the existing archive. The timeline describes topic development, not a verified forecasting track record.</p>${tracks.map((t,i)=>`<section class="track" id="${t.id}"><div class="track-title"><p class="eyebrow">DIRECTION 0${i+1}</p><h2>${esc(t.title)}</h2><p>${esc(t.question)}</p></div><div><div class="position"><p class="eyebrow">CURRENT RESEARCH FOCUS</p><h3>${esc(t.position)}</h3></div><div class="track-details"><div><h4>Open question</h4><p>${esc(t.uncertainty)}</p></div><div><h4>Signals to follow</h4><p>${esc(t.signals)}</p></div></div><div class="evolution">${t.history.map(h=>`<div><time>${esc(h.date)}</time><p>${esc(h.text)}</p></div>`).join('')}</div>${entries.some(p=>p.topic===t.topic)?entries.filter(p=>p.topic===t.topic).map(row).join(''):'<p class="muted">Supporting material is being prepared for publication.</p>'}</div></section>`).join('')}<span id="ai-product-strategy"></span></section>`,'Future Map');
page('projects.html','Projects',intro('RESEARCH INTO PRACTICE','Projects<span>.</span>','Structured investigations into AI workloads, research methods and emerging systems.')+`<section class="wrap">${projects.map((p,i)=>`<article class="project" id="${p.id}"><div><p class="eyebrow">0${i+1} / <span class="status">${p.status}</span></p><h2>${esc(p.title)}</h2></div><div><h4>Question</h4><p>${esc(p.problem)}</p><h4>Approach</h4><p>${esc(p.method)}</p><h4>${p.status==='Active'?'Published output':'Planned output'}</h4><p>${esc(p.output)}</p>${p.link?`<a class="primary-link" href="${p.link}">View research ↗</a>`:''}</div></article>`).join('')}</section>`,'Projects');
page('about.html','About',intro('ABOUT ME','Donald Lai<span>.</span>','I am interested in how technical constraints become product decisions, industry structure and market consequences.')+`<section class="wrap about-layout"><aside><div class="monogram" aria-hidden="true">DL<span>.</span></div><a href="https://x.com/donaldlai3000">X · @donaldlai3000 ↗</a><a href="https://github.com/LLL1111111">GitHub · LLL1111111 ↗</a></aside><div class="prose"><p class="eyebrow">PERSONAL INTRODUCTION</p><h2>Systems first.<br>Consequences next.</h2><p>This site brings together my public thinking on AI infrastructure, agents, product strategy, public markets and the longer-term direction of technology.</p><p>The recurring question is simple: where are the real bottlenecks moving, and what changes once people start building around them?</p><h3>How I approach research</h3><p>I connect technical detail with the wider system: how a workload behaves, what infrastructure it needs, what products become possible and how the industry may respond. My writing sits between research memo, strategy note and public notebook.</p><p>The Future Map collects the questions I continue to follow. The Insights library holds the original research and supporting material.</p><hr><p class="eyebrow">BEYOND THE RESEARCH</p><h2>Football & sport.</h2><p>I enjoy sport, especially football: the competition, the culture and the interaction of tactics, talent and teamwork.</p><p>Systems, constraints and feedback loops are interesting on the pitch as well as in technology.</p></div></section>`,'About');
page('notes.html','Notes',intro('PUBLIC NOTEBOOK','Notes on X<span>.</span>','Short observations and conversations from @donaldlai3000.')+`<section class="wrap notes"><div id="x-feed"><p id="x-status" role="status">Loading public posts…</p></div><p id="x-fallback" hidden>X has not made the feed available in this browser. <a href="https://x.com/donaldlai3000">Read the original posts on X ↗</a></p></section>`,'Insights');
for(const p of entries) page('posts/'+p.slug+'.html',p.title,`<article class="wrap reading"><a href="../insights.html">← All insights</a><header class="article-header"><p class="eyebrow">${esc(p.type)} · ${esc(p.topic)}</p><h1>${esc(p.title)}</h1><p class="lead">${esc(p.summary)}</p><p class="metadata">Donald Lai · Originally written ${esc(p.date)}${p.publishedAt?' · Published '+esc(p.publishedAt):''}</p></header><div class="prose">${marked.parse(p.body||'')}</div>${p.attachment?`<section class="document"><div class="section-heading"><h2>Original research</h2><a class="primary-link" href="..${p.attachment}" download>Download ${p.attachment.split('.').pop().toUpperCase()} ↓</a></div>${p.attachment.toLowerCase().endsWith('.pdf')?`<iframe loading="lazy" title="${esc(p.title)} PDF" src="..${p.attachment}"></iframe><a href="..${p.attachment}" target="_blank" rel="noopener">Open PDF in a new tab ↗</a>`:''}</section>`:''}<section class="related"><h2>Continue exploring</h2><a href="../future.html#${tracks.find(t=>t.topic===p.topic)?.id||tracks[0].id}">Explore the related Future Map direction ↗</a>${entries.filter(e=>e.slug!==p.slug&&e.topic===p.topic).map(e=>`<p><a href="${e.slug}.html">${esc(e.title)}</a></p>`).join('')}</section></article>`,'Insights',p.summary);
for(const [old,target] of Object.entries({'blog.html':'insights.html','essays.html':'insights.html','research.html':'future.html','cv.html':'about.html'})) fs.writeFileSync('dist/'+old,`<!doctype html><html lang="en"><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=${target}"><title>Page moved</title><a href="${target}">Continue</a><script>location.replace('${target}'+location.search+location.hash)</script></html>`);
const urls=['index.html','insights.html','future.html','projects.html','about.html','notes.html',...entries.map(p=>'posts/'+p.slug+'.html')];
fs.writeFileSync('dist/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`<url><loc>https://lll1111111.github.io/${u}</loc></url>`).join('')}</urlset>`);
fs.writeFileSync('dist/feed.xml',`<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>Donald Lai | Insights</title><link>https://lll1111111.github.io/</link><description>AI systems, emerging technology and long-term thinking.</description>${entries.map(p=>`<item><title>${esc(p.title)}</title><link>https://lll1111111.github.io/posts/${p.slug}.html</link><guid>https://lll1111111.github.io/posts/${p.slug}.html</guid><description>${esc(p.summary)}</description></item>`).join('')}</channel></rss>`);
fs.writeFileSync('dist/robots.txt','User-agent: *\nAllow: /\nSitemap: https://lll1111111.github.io/sitemap.xml\n');
fs.writeFileSync('dist/.nojekyll','');
console.log(`Built ${urls.length} pages; ${entries.length} published entries; ${all.length-entries.length} drafts excluded.`);
